### ISSUE TITLE
Too many lines

### ISSUE THREAD

**Issue by 0x000C0A71** [Nnmjywg/F2C#1]
My AMD gpu can‘t render all lines. And this has a lot. My PC can‘t run it. Please provide a version with less lines, so I can use this highly suffisticated piece of software. Or perhaps it is not possible to remove the bloat, since it‘s written in c. Perhaps another programing language would‘ve been more suitable for the job. I‘d suggest something along the lines of python. It‘s easy to learn, modern, quick to prototype, runs like butter, is avalable on nearly every platform and is straight forward.
Please look int this issue to better yourself as a programer
XerneraC

**Comment by Nnmjywg** [comment]
Why don’t you write it and take a look at the ram usage?

Well, if your potato AMD PC can’t run C, it most certainly won’t be able to run python.
